In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from collections import Counter



In [65]:
pd.set_option('display.max_rows', 20)
pd.set_option('display.max_columns', None)

In [5]:
# Load data from https://archive.ics.uci.edu/ml/machine-learning-databases/00240/UCI%20HAR%20Dataset.zip
# and unzip all files into a new “HARDataset”directory in current working directory. 

In [6]:
# In the "train" data folder, there are 
# 9 files recording 9 measurements in "Inertial Signals" folder, these are predictor data (independant variables), shape (7352 x 128);
# and 1 y_train file, this is the target (dependant variables), shape (7352 x 1).

# Similar with "test" data folder.

# Let's read one training file and one testing file and have a quick look:

X_train_file = r'C:\Users\80136730\1dCNN\HARDataset\UCI HAR Dataset\train\Inertial Signals\body_acc_x_train.txt' #there are 8 more
y_train_file = r'C:\Users\80136730\1dCNN\HARDataset\UCI HAR Dataset\train\y_train.txt'
X_test_file = r'C:\Users\80136730\1dCNN\HARDataset\UCI HAR Dataset\test\Inertial Signals\body_acc_x_test.txt'  #there are 8 more
y_test_file = r'C:\Users\80136730\1dCNN\HARDataset\UCI HAR Dataset\test\y_test.txt'

In [7]:
X_train1 = pd.read_csv(X_train_file, header=None, delim_whitespace=True)
y_train1 = pd.read_csv(y_train_file, header=None, delim_whitespace=True)

In [9]:
X_train1.shape, y_train1.shape

((7352, 128), (7352, 1))

In [11]:
X_train1.head()

0         1         2         3         4         5         6    \
0  0.000181  0.010139  0.009276  0.005066  0.010810  0.004045  0.004757   
1  0.001094  0.004550  0.002879  0.002247  0.003305  0.002416  0.001619   
2  0.003531  0.002285 -0.000420 -0.003738 -0.006706 -0.003148  0.000733   
3 -0.001772 -0.001311  0.000388  0.000408 -0.000355  0.000998  0.001109   
4  0.000087 -0.000272  0.001022  0.003126  0.002284  0.000885  0.001933   

        7         8         9    ...       118       119       120       121  \
0  0.006214  0.003307  0.007572  ...  0.001412 -0.001509  0.000060  0.000435   
1  0.000981  0.000009 -0.000363  ... -0.000104 -0.000141  0.001333  0.001541   
2  0.000668  0.002162 -0.000946  ...  0.000661  0.001853 -0.000268 -0.000394   
3 -0.003149 -0.008882 -0.010483  ...  0.000458  0.002103  0.001358  0.000820   
4  0.002270  0.002247  0.002175  ...  0.002529  0.003518 -0.000248 -0.002761   

        122       123       124       125       126       127  
0 -0.000819  0.000228 -0.000300 -0.001147 -0.000222  0.001576  
1  0.001077 -0.000736 -0.003767 -0.004646 -0.002941 -0.001599  
2 -0.000279 -0.000316  0.000144  0.001246  0.003117  0.002178  
3 -0.000212 -0.001915 -0.001631 -0.000867 -0.001172 -0.000028  
4  0.000252  0.003752  0.001626 -0.000698 -0.001223 -0.003328  

[5 rows x 128 columns]

In [27]:
count = dict(Counter(y_train1[0]))
for key, value in sorted(count.items()):
    print (key, value) 

1 1226
2 1073
3 986
4 1286
5 1374
6 1407


In [28]:
count

{5: 1374, 4: 1286, 6: 1407, 1: 1226, 3: 986, 2: 1073}

In [29]:
my_array = np.random.randint(10, size=(3,4))

In [30]:
my_df = pd.DataFrame(my_array)

In [31]:
my_df

0  1  2  3
0  0  8  3  7
1  6  5  5  6
2  2  0  4  5

In [32]:
my_df.values

array([[0, 8, 3, 7],
       [6, 5, 5, 6],
       [2, 0, 4, 5]])

In [33]:
my_array

array([[0, 8, 3, 7],
       [6, 5, 5, 6],
       [2, 0, 4, 5]])

In [34]:
a1 = np.random.randint(9, size=(3,2))
a2 = np.random.randint(10,19, size=(3,2))

In [35]:
a1

array([[8, 3],
       [1, 1],
       [3, 1]])

In [36]:
a2

array([[13, 17],
       [18, 13],
       [16, 12]])

In [37]:
s1 = np.dstack((a1, a2))

In [38]:
s1

array([[[ 8, 13],
        [ 3, 17]],

       [[ 1, 18],
        [ 1, 13]],

       [[ 3, 16],
        [ 1, 12]]])

In [39]:
a1.shape, s1.shape

((3, 2), (3, 2, 2))

In [40]:
s2 = np.dstack((s1, a2))

In [41]:
s2

array([[[ 8, 13, 13],
        [ 3, 17, 17]],

       [[ 1, 18, 18],
        [ 1, 13, 13]],

       [[ 3, 16, 16],
        [ 1, 12, 12]]])

In [42]:
np.dstack((a1, a2, a2))

array([[[ 8, 13, 13],
        [ 3, 17, 17]],

       [[ 1, 18, 18],
        [ 1, 13, 13]],

       [[ 3, 16, 16],
        [ 1, 12, 12]]])

In [43]:
x = np.array([1,3,4,2])

In [44]:
x

array([1, 3, 4, 2])

In [45]:
x.shape

(4,)

In [46]:
y=np.dstack(x)

In [47]:
y

array([[[1, 3, 4, 2]]])

In [48]:
y.shape

(1, 1, 4)

In [49]:
# X_train_file = r'C:\Users\80136730\1dCNN\HARDataset\UCI HAR Dataset\train\Inertial Signals\body_acc_x_train.txt' 
# there are 8 more
# y_train_file = r'C:\Users\80136730\1dCNN\HARDataset\UCI HAR Dataset\train\y_train.txt'

# X_test_file = r'C:\Users\80136730\1dCNN\HARDataset\UCI HAR Dataset\test\Inertial Signals\body_acc_x_test.txt'  
# there are 8 more
# y_test_file = r'C:\Users\80136730\1dCNN\HARDataset\UCI HAR Dataset\test\y_test.txt'

def read_file(filepath):
    return pd.read_csv(filepath, header=None, delim_whitespace=True).values

def dstack_files(subset, filenames):
    file_list = []
    for name in filenames:
        file = read_file(subset + name)
        file_list.append(file)
    return np.dstack(file_list)

def load_group(dataset, group):
    subset = dataset + group + '/Inertial Signals/'
    filenames = ['body_acc_x_'+group+'.txt', 'body_acc_y_'+group+'.txt','body_acc_z_'+group+'.txt',
                 'body_gyro_x_'+group+'.txt', 'body_gyro_y_'+group+'.txt','body_gyro_z_'+group+'.txt',
                 'total_acc_x_'+group+'.txt', 'total_acc_y_'+group+'.txt','total_acc_z_'+group+'.txt']
    X = dstack_files(subset, filenames)
    y = read_file(dataset + group + '/y_' + group + '.txt')
    return X, y

def load_data(dataset=r'C:/Users/80136730/1dCNN/HARDataset/UCI HAR Dataset/'):
    X_train, y_train = load_group(dataset, 'train')
    X_test, y_test = load_group(dataset, 'test')
    return X_train, y_train, X_test, y_test 

In [50]:
Xtrain, ytrain, Xtest, ytest = load_data()

In [51]:
ytest

array([[5],
       [5],
       [5],
       ...,
       [2],
       [2],
       [2]], dtype=int64)

In [52]:
Xtrain.shape, ytrain.shape, Xtest.shape, ytest.shape

((7352, 128, 9), (7352, 1), (2947, 128, 9), (2947, 1))

In [53]:
yt = np.ndarray.tolist(ytrain)

In [54]:
tl = [item for sublist in yt for item in sublist]

In [55]:
Counter(tl).items()

dict_items([(5, 1374), (4, 1286), (6, 1407), (1, 1226), (3, 986), (2, 1073)])

In [66]:
Xtest[1]

array([[ 0.00927963,  0.00665052, -0.02631933, ...,  0.9991921 ,
        -0.2649349 ,  0.1256164 ],
       [ 0.00492971,  0.01864973, -0.02688753, ...,  0.9946787 ,
        -0.2532142 ,  0.1256249 ],
       [ 0.0039536 ,  0.0155395 , -0.03663861, ...,  0.9935518 ,
        -0.2565887 ,  0.1163814 ],
       ...,
       [ 0.0077876 ,  0.00473062,  0.01412899, ...,  1.001861  ,
        -0.2619359 ,  0.1527878 ],
       [ 0.00343349, -0.00461985,  0.00133805, ...,  0.9975208 ,
        -0.2713225 ,  0.1398428 ],
       [-0.00123868, -0.01322889, -0.01703861, ...,  0.9928615 ,
        -0.2799715 ,  0.1213135 ]])

In [67]:
Xtest[1][1]

array([ 0.00492971,  0.01864973, -0.02688753,  0.1752221 , -0.09536355,
        0.04334361,  0.9946787 , -0.2532142 ,  0.1256249 ])

In [68]:
len(Xtest[1])

128

In [143]:
# one hot encode y
ytrain_hot = to_categorical(ytrain-1, num_classes=6)
ytest_hot = to_categorical(ytest-1, num_classes=6)

In [58]:
ytrain_hot.shape

(7352, 6)

In [59]:
ytrain_hot[1]

array([0., 0., 0., 0., 1., 0.], dtype=float32)

In [60]:
to_categorical([1,3])

array([[0., 1., 0., 0.],
       [0., 0., 0., 1.]], dtype=float32)

In [120]:
np.arange(4)+1

array([1, 2, 3, 4])